<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Location::insert([
            [
                'name' => 'La Cancha',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '5',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 15,
                'address' => 'Av. Wilson',
                'map_latitude' => -12.067322,
                'map_longitude' => -77.033723,
                'active' => TRUE,
                'company_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'La de Loza',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '8',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 14,
                'address' => 'Av. Mexico',
                'map_latitude' => -12.068605,
                'map_longitude' => -77.022909,
                'active' => TRUE,
                'company_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Complejo La Caleta 2',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 40,
                'address' => 'Av. Próceres Cuadra 5',
                'map_latitude' => -12.15264,
                'map_longitude' => -76.990020,
                'active' => TRUE,
                'company_id' => 2,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Sport Point',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 3,
                'address' => 'Playa las cascadas s/n Costa Verde',
                'map_latitude' => -12.140748,
                'map_longitude' => -77.028468,
                'active' => TRUE,
                'company_id' => 3,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Club Maracana',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 16,
                'address' => 'Coronel Joaquin, S/N',
                'map_latitude' => -12.088043,
                'map_longitude' => -77.041733,
                'active' => TRUE,
                'company_id' => 4,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Campo Rimac',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 28,
                'address' => 'Avenida La Alameda de los Descalzos',
                'map_latitude' => -12.036245,
                'map_longitude' => -77.026205,
                'active' => TRUE,
                'company_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Complejo Deportivo San Pio X',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 17,
                'address' => 'Avenida Manuel Gonzales Prada, 269',
                'map_latitude' => -11.996191,
                'map_longitude' => -77.066328,
                'active' => TRUE,
                'company_id' => 6,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Campo Cultural Lima',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 7,
                'address' => 'Las Capironas 321, Villa Militar Matellini',
                'map_latitude' => -12.174981,
                'map_longitude' => -77.008770,
                'active' => TRUE,
                'company_id' => 7,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Country Club Chama',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 40,
                'address' => 'Enrique León García, 559',
                'map_latitude' => -12.124883,
                'map_longitude' => -76.994695,
                'active' => TRUE,
                'company_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Sport Plaza',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 2,
                'address' => 'Avenida Nicolas Ayllon, 3080',
                'map_latitude' => -12.057780,
                'map_longitude' => -76.969289,
                'active' => TRUE,
                'company_id' => 9,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'La Cantera - Sede Industrial',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 35,
                'address' => 'Av. Industrial 3652',
                'map_latitude' => -11.991336,
                'map_longitude' => -77.059150,
                'active' => TRUE,
                'company_id' => 10,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'La Bombonera F - 7',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 41,
                'address' => 'Avenida Angamos Este, 1551',
                'map_latitude' => -12.112569,
                'map_longitude' => -77.014671,
                'active' => TRUE,
                'company_id' => 11,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Entrepelotas Club',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 13,
                'address' => 'Avenida Los Frutale, 561',
                'map_latitude' => -12.063924,
                'map_longitude' => -76.964883,
                'active' => TRUE,
                'company_id' => 12,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Macho Center',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 40,
                'address' => 'Avenida Jacarandá 600 Urb. Casuarinas',
                'map_latitude' => -12.123776,
                'map_longitude' => -76.975171,
                'active' => TRUE,
                'company_id' => 13,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'La Cantera - Sede Los Andes',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 35,
                'address' => 'Calle Los Andes, 378',
                'map_latitude' => -11.991058,
                'map_longitude' =>  -77.061372,
                'active' => TRUE,
                'company_id' => 10,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Centro Deportivo San Francisco',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 43,
                'address' => 'Av. Pachacutec 4850, Tablada de Lurín',
                'map_latitude' => -12.191017,
                'map_longitude' => -76.936039,
                'active' => TRUE,
                'company_id' => 14,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'La Pelotera',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 40,
                'address' => 'Av. Los Vicus 760 La Capullana',
                'map_latitude' => -12.139811,
                'map_longitude' => -77.005129,
                'active' => TRUE,
                'company_id' => 15,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Marceti Club',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 2,
                'address' => 'Avenida Husares De Junín',
                'map_latitude' => -12.034754,
                'map_longitude' => -76.923404,
                'active' => TRUE,
                'company_id' => 16,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Asociación de Residentes Pando I Etapa',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 36,
                'address' => 'Pedro Villar Córdova 222',
                'map_latitude' => -12.076558,
                'map_longitude' => -77.086384,
                'active' => TRUE,
                'company_id' => 17,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Soccer Club del Perú - Jockey',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 40,
                'address' => 'Av. El Derby S/N',
                'map_latitude' => -12.097153,
                'map_longitude' => -76.975014,
                'active' => TRUE,
                'company_id' => 18,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Picapiedra Soccer',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 40,
                'address' => 'Av Guardia Civil Sur',
                'map_latitude' => -12.168618,
                'map_longitude' => -76.991434,
                'active' => TRUE,
                'company_id' => 19,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Complejo Liseo Naval',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 30,
                'address' => 'Liseo Naval Puerta N°3',
                'map_latitude' => -12.095369,
                'map_longitude' => -76.997519,
                'active' => TRUE,
                'company_id' => 20,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Complejo Deportivo la 9',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 36,
                'address' => 'Av. Venezuela cdra. 34 S/N',
                'map_latitude' => -12.061756,
                'map_longitude' => -77.089560,
                'active' => TRUE,
                'company_id' => 21,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'VillaSport Los Precursores',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 40,
                'address' => 'Jr. Jose Aguilar Segura S/N',
                'map_latitude' => -12.158147,
                'map_longitude' => -76.984959,
                'active' => TRUE,
                'company_id' => 22,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Villa Sport Club',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 21,
                'address' => 'Enrique Caballero 376',
                'map_latitude' => -12.125042,
                'map_longitude' => -77.004694,
                'active' => TRUE,
                'company_id' => 23,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'La Cancha Perú',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 40,
                'address' => 'Av Pio XII 123',
                'map_latitude' => -12.095148,
                'map_longitude' => -76.967593,
                'active' => TRUE,
                'company_id' => 24,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Futbol Plaza',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 30,
                'address' => 'Av. La República 110, Monterrico',
                'map_latitude' => -12.099491,
                'map_longitude' => -76.976818,
                'active' => TRUE,
                'company_id' => 25,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Centenario FC',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 15,
                'address' => 'Jr. Emilio Rossel 670 Urb Las Brisas',
                'map_latitude' => -12.064244,
                'map_longitude' =>  -77.067975,
                'active' => TRUE,
                'company_id' => 26,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Deport Center - Paz Soldan',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 15,
                'address' => 'Calle Los Descalzos Cuadra 3',
                'map_latitude' => -12.036474,
                'map_longitude' => -77.023155,
                'active' => TRUE,
                'company_id' => 27,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'La numero 10',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 41,
                'address' => 'Pablo Nerura 110',
                'map_latitude' => -12.113187,
                'map_longitude' => -77.007717,
                'active' => TRUE,
                'company_id' => 28,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Campo Deportivo Jali Sports',
                'phone' => '999888777',
                'mobile' => '987654321',
                'parking' => '0',
                'country_id' => 1,
                'city_id' => 1,
                'district_id' => 13,
                'address' => 'Calle Las Amapolas 180',
                'map_latitude' => -12.082482,
                'map_longitude' => -76.955791,
                'active' => TRUE,
                'company_id' => 28,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);
    }}
